name: booking
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-configdb:
    driver: local

networks:
  default:
    driver: bridge